### ISSUE TITLE
Not working in Chrome (and Firefox)

### ISSUE THREAD

**Issue by sn0opy** [jakiestfu/Blur.js#1]
Chrome is completely blocking the script, if you want to access the target also as source. Firefox instead still shows an error, with an information about JS access to `file://`.

Any fix?

**Comment by jakiestfu** [comment]
@sn0opy, I believe it has to do with trying to use it on a local file system. Try uploading it to a server, and try using an image on the same server, there is some Cross Origin Policies in effect so you cannot blur an external image. Let me know how that turns out and I will take a closer work if that does not fix it.

**Comment by sn0opy** [comment]
As you said, it's working on an external server.

But it looks like there's another issue with with `background-size: cover;`. The background is re-arranged and not vertically centered anymore as it was before.
